import * as T from 'three';
/** Canvas fallback for environments without WebGL. Uses the same source geometry and camera. */
export class SoftwareRenderer {
 domElement=document.createElement('canvas');outputColorSpace='';toneMapping=0;toneMappingExposure=1;private ctx:CanvasRenderingContext2D;private width=1;private height=1;private stamp='';private last=0;
 constructor(){this.ctx=this.domElement.getContext('2d')!;if(!this.ctx)throw new Error('Canvas unavailable')}
 setPixelRatio(_n:number){} setSize(w:number,h:number){this.width=w;this.height=h;this.domElement.width=w;this.domElement.height=h;this.domElement.style.width=w+'px';this.domElement.style.height=h+'px';this.stamp=''}dispose(){}
 render(scene:T.Scene,camera:T.PerspectiveCamera){const now=performance.now();if(now-this.last<70)return;scene.updateMatrixWorld();camera.updateMatrixWorld();const all:T.Mesh[]=[];scene.traverseVisible(o=>{if(o instanceof T.Mesh)all.push(o)});const stamp=camera.matrixWorld.elements.map(n=>n.toFixed(4)).join(',')+all.map(m=>m.position.toArray().map(n=>n.toFixed(4)).join(',')+m.id+m.geometry.id+(m.material as T.MeshStandardMaterial).color?.getHex()+(m.material as T.MeshStandardMaterial).emissive?.getHex()).join('|');if(stamp===this.stamp)return;this.last=now;this.stamp=stamp;const ctx=this.ctx,w=this.width,h=this.height;ctx.clearRect(0,0,w,h);const vp=new T.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse);const light=new T.Vector3(-.6,1,.9).normalize();const normalMat=new T.Matrix3();const normal=new T.Vector3(),v=new T.Vector3(),a=new T.Vector3(),b=new T.Vector3(),c=new T.Vector3();const faces:{xy:number[];z:number;color:string}[]=[];
 for(const m of all){const geo=m.geometry,pos=geo.getAttribute('position'),norm=geo.getAttribute('normal'),idx=geo.index;if(!pos)continue;const matrix=new T.Matrix4().multiplyMatrices(vp,m.matrixWorld);normalMat.getNormalMatrix(m.matrixWorld);const coords=new Float32Array(pos.count*3);for(let i=0;i<pos.count;i++){v.fromBufferAttribute(pos,i).applyMatrix4(matrix);coords[i*3]=(v.x+1)*w/2;coords[i*3+1]=(1-v.y)*h/2;coords[i*3+2]=v.z}const mat=m.material as T.MeshStandardMaterial,base=mat.color;const count=idx?idx.count:pos.count;
 for(let j=0;j<count;j+=3){const ia=idx?idx.getX(j):j,ib=idx?idx.getX(j+1):j+1,ic=idx?idx.getX(j+2):j+2;const ax=coords[ia*3],ay=coords[ia*3+1],az=coords[ia*3+2],bx=coords[ib*3],by=coords[ib*3+1],bz=coords[ib*3+2],cx=coords[ic*3],cy=coords[ic*3+1],cz=coords[ic*3+2];if(az>1||bz>1||cz>1||az< -1||bz< -1||cz< -1)continue;if((ax<0&&bx<0&&cx<0)||(ax>w&&bx>w&&cx>w)||(ay<0&&by<0&&cy<0)||(ay>h&&by>h&&cy>h))continue;const area=(bx-ax)*(cy-ay)-(by-ay)*(cx-ax);if(Math.abs(area)<.09)continue;
 if(norm){normal.fromBufferAttribute(norm,ia).add(v.fromBufferAttribute(norm,ib)).add(v.fromBufferAttribute(norm,ic)).applyMatrix3(normalMat).normalize()}else{a.fromBufferAttribute(pos,ia);b.fromBufferAttribute(pos,ib);c.fromBufferAttribute(pos,ic);normal.copy(b).sub(a).cross(c.sub(a)).applyMatrix3(normalMat).normalize()}const brightness=.4+.6*Math.max(0,normal.dot(light));const color=base.clone().multiplyScalar(brightness);if(mat.emissive)color.add(mat.emissive.clone().multiplyScalar(mat.emissiveIntensity));faces.push({xy:[ax,ay,bx,by,cx,cy],z:(az+bz+cz)/3,color:color.getStyle()});}}
 faces.sort((a,b)=>b.z-a.z);ctx.lineWidth=.45;for(const f of faces){ctx.beginPath();ctx.moveTo(f.xy[0],f.xy[1]);ctx.lineTo(f.xy[2],f.xy[3]);ctx.lineTo(f.xy[4],f.xy[5]);ctx.closePath();ctx.fillStyle=f.color;ctx.strokeStyle=f.color;ctx.fill();ctx.stroke()}
 }
}
