import {useEffect,useRef} from 'react';
import * as T from 'three';
import {isShown,planeAxis,sectionGeometry,inRegion} from './sections';
import {studyCategory} from './study-colors';
import {SoftwareRenderer} from './software-renderer';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import type {Atlas,Part,SceneState} from './types';
const specs=[['Cervical','C',8,.105],['Thoracic','T',12,.195],['Lumbar','L',5,.065],['Sacral','S',5,.04],['Coccygeal','Co',1,.01]] as const;
export const cordParts:Part[]=[];let y=1.544,idx=0;
for(const [region,prefix,count,length] of specs){for(let i=0;i<count;i++){const h=length/count;cordParts.push({id:`cord-${prefix}${i+1}`,name:`${prefix}${i+1} · ${region} cord segment`,region,segment:idx++,group:'Spinal cord',kind:'Schematic segment',color:region==='Cervical'?'#dfc696':region==='Thoracic'?'#cdb786':region==='Lumbar'?'#e7c798':'#cbb38d',refs:[{lecture:4,slide:3}],bounds:[[-.008,y-h,-.055],[.008,y,-.039]]});y-=h}}
interface Props {atlas:Atlas;state:SceneState;onSelect:(id:string)=>void;onReady:()=>void;onError:(s:string)=>void}
export default function Scene({atlas,state,onSelect,onReady,onError}:Props){
 const host=useRef<HTMLDivElement>(null),latest=useRef(state),select=useRef(onSelect);latest.current=state;select.current=onSelect;
 useEffect(()=>{const el=host.current!;let dead=false,frame=0,amount=0,loaded=false,key='',lastFocus='';const abort=new AbortController();let renderer:T.WebGLRenderer|SoftwareRenderer;
 try{renderer=new T.WebGLRenderer({antialias:true,alpha:true});}catch{try{renderer=new SoftwareRenderer()}catch{onError('The 3D viewer could not start in this browser. Please try another browser.');return}}
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;renderer.domElement.setAttribute('aria-label','Interactive brain and spinal cord model');el.appendChild(renderer.domElement);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.001,30),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.1;controls.minDistance=.025;controls.maxDistance=6;controls.autoRotateSpeed=.55;
 scene.add(new T.HemisphereLight('#edf2ff','#746b72',2.1));const keylight=new T.DirectionalLight('#fff2df',3);keylight.position.set(-1,3,2);scene.add(keylight);const rim=new T.DirectionalLight('#c6deff',2.5);rim.position.set(2,2,-1);scene.add(rim);
 const pedestal=new T.Group();const disc=new T.Mesh(new T.CylinderGeometry(.205,.215,.012,100),new T.MeshStandardMaterial({color:'#272e3b',metalness:.55,roughness:.42}));disc.position.y=1.105;pedestal.add(disc);const ring=new T.Mesh(new T.RingGeometry(.194,.195,128),new T.MeshBasicMaterial({color:'#718f9c',side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=1.112;pedestal.add(ring);scene.add(pedestal);
 const meshes:T.Mesh[]=[],geometries:T.BufferGeometry[]=[],materials:T.MeshStandardMaterial[]=[],labels:HTMLDivElement[]=[],centers=atlas.parts.map(p=>new T.Vector3().fromArray(p.bounds[0]).add(new T.Vector3().fromArray(p.bounds[1])).multiplyScalar(.5)),targets:T.Vector3[]=atlas.parts.map(()=>new T.Vector3());
 const labelRoot=document.createElement('div');labelRoot.className='mesh-labels';el.appendChild(labelRoot);const tip=document.createElement('div');tip.className='mesh-tooltip';tip.hidden=true;el.appendChild(tip);
 const cordZ=(yy:number)=>-.044-0.012*Math.sin((1.544-yy)/.415*Math.PI);
 function cordGeometry(p:Part){const y0=p.bounds[0][1],y1=p.bounds[1][1],h=y1-y0,yy=(y0+y1)/2;const r=p.region==='Cervical'?.0065:p.region==='Lumbar'?.007:p.region==='Thoracic'?.0055:p.region==='Sacral'?.0045:.002;const bottom=p.region==='Coccygeal'?.0008:r;const g=new T.CylinderGeometry(r,bottom,h*.985,24,1);g.scale(1,1,.83);g.translate(-.00065,yy,cordZ(yy));g.computeBoundingBox();p.bounds=[g.boundingBox!.min.toArray(),g.boundingBox!.max.toArray()];return g;}
 async function load(){try{const response=await fetch('models/neuro.bin',{signal:abort.signal});if(!response.ok)throw Error();const buf=await response.arrayBuffer();if(dead)return;atlas.parts.forEach((p,i)=>{let g:T.BufferGeometry;if(p.segment!==undefined){g=cordGeometry(p);centers[i].set(...p.bounds[0] as [number,number,number]).add(new T.Vector3().fromArray(p.bounds[1])).multiplyScalar(.5)}else{g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(new Float32Array(buf,p.positions!,p.vertexCount!*3),3));g.setAttribute('normal',new T.BufferAttribute(new Int16Array(buf,p.normals!,p.vertexCount!*3),3,true));g.setIndex(new T.BufferAttribute(new Uint32Array(buf,p.indices!,p.indexCount!),1));}g.computeBoundingSphere();geometries.push(g);const mat=new T.MeshPhysicalMaterial({color:p.color,roughness:.52,metalness:0,clearcoat:.16,clearcoatRoughness:.48,side:T.DoubleSide});materials.push(mat);const mesh=new T.Mesh(g,mat);mesh.userData.index=i;scene.add(mesh);meshes.push(mesh);const label=document.createElement('div');label.className='mesh-label';label.textContent=p.name;labelRoot.appendChild(label);labels.push(label)});loaded=true;onReady();fit();}catch(e){if(!dead)onError('The anatomy model could not load. Reload to try again.')}}load();
 const shown=isShown;let sectionKey='';const cuts:T.BufferGeometry[]=[];function updateSections(s:SceneState){const k=s.plane+s.region+s.slice+s.visible.join('|');if(k===sectionKey)return;sectionKey=k;cuts.forEach(g=>g.dispose());cuts.length=0;if(s.plane==='none'){meshes.forEach((m,i)=>m.geometry=geometries[i]);return}const axis=planeAxis(s.plane);const parts=atlas.parts.filter(p=>inRegion(p,s.region)&&s.visible.includes(p.group));const min=Math.min(...parts.map(p=>p.bounds[0][axis])),max=Math.max(...parts.map(p=>p.bounds[1][axis]));const val=min+(max-min)*s.slice/100;meshes.forEach((m,i)=>{const g=sectionGeometry(geometries[i],axis,val);cuts.push(g);m.geometry=g})}
 function layout(){const s=latest.current;const indexes=atlas.parts.map((p,i)=>i).filter(i=>shown(atlas.parts[i],s));const cards=indexes.map(i=>({i,w:Math.max(.018,atlas.parts[i].bounds[1][0]-atlas.parts[i].bounds[0][0])+.018,h:Math.max(.018,atlas.parts[i].bounds[1][1]-atlas.parts[i].bounds[0][1])+.021}));cards.sort((a,b)=>atlas.parts[a.i].group.localeCompare(atlas.parts[b.i].group)||b.h-a.h);const area=cards.reduce((a,c)=>a+c.w*c.h,0);const width=Math.max(.15,Math.sqrt(area*camera.aspect)*1.07);let x=0,y=0,row=0,maxX=0;cards.forEach(c=>{if(x>0&&x+c.w>width){x=0;y+=row;row=0}targets[c.i].set(x+c.w/2,-y-c.h/2,0);x+=c.w;row=Math.max(row,c.h);maxX=Math.max(maxX,x)});const height=y+row;cards.forEach(c=>targets[c.i].add(new T.Vector3(-maxX/2,1.48+height/2,0)))}
 const direction=()=>latest.current.plane==='sagittal'?new T.Vector3(1,0,0):latest.current.plane==='horizontal'?new T.Vector3(0,1,.0001):latest.current.plane==='coronal'?new T.Vector3(0,0,1):latest.current.view==='inferior'?new T.Vector3(0,-1,.001):latest.current.view==='front'?new T.Vector3(0,.03,1):latest.current.view==='back'?new T.Vector3(0,.03,-1):latest.current.view==='side'?new T.Vector3(1,.02,0):latest.current.view==='top'?new T.Vector3(0,1,.001):new T.Vector3(.7,.22,1).normalize();
 function fit(){if(!loaded)return;const s=latest.current,box=new T.Box3();atlas.parts.forEach((p,i)=>{if(shown(p,s)){const b=new T.Box3(new T.Vector3().fromArray(p.bounds[0]),new T.Vector3().fromArray(p.bounds[1]));box.union(b.translate(meshes[i].position))}});if(box.isEmpty())return;camera.up.set(0,(s.plane==='horizontal'||s.view==='top'||s.view==='inferior')?0:1,(s.plane==='horizontal'||s.view==='top'||s.view==='inferior')?1:0);const size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3());const dim=(s.plane==='horizontal'||s.view==='top'||s.view==='inferior')?Math.max(size.z,size.x/camera.aspect):(s.plane==='sagittal'||s.view==='side')?Math.max(size.y,size.z/camera.aspect):Math.max(size.y,size.x/camera.aspect);const distance=Math.max(.05,dim/(2*Math.tan(T.MathUtils.degToRad(camera.fov/2)))*(s.brainOnly?1.4:1.23)+size.z*.3);controls.target.copy(center);camera.position.copy(center).addScaledVector(direction(),distance);controls.update()}
 function resize(){const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();key='';layout();fit()}const observer=new ResizeObserver(resize);observer.observe(el);resize();
 const ray=new T.Raycaster(),pointer=new T.Vector2();let down=[0,0],drag=false;
 function pick(e:PointerEvent){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(meshes.filter(m=>m.visible),false);return hits[0]?.object.userData.index as number|undefined}
 function pointerDown(e:PointerEvent){down=[e.clientX,e.clientY];drag=false;tip.hidden=true}
 function pointerMove(e:PointerEvent){if(e.buttons){drag=drag||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5;tip.hidden=true;return}const i=pick(e);tip.hidden=i===undefined;renderer.domElement.style.cursor=i===undefined?'grab':'pointer';if(i!==undefined){tip.textContent=latest.current.hideNames?'Click to test your recall':atlas.parts[i].name;const r=el.getBoundingClientRect();tip.style.left='12px';tip.style.top='76px'}}
 function pointerUp(e:PointerEvent){if(drag||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const i=pick(e);if(i!==undefined)select.current(atlas.parts[i].id)}
 renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointermove',pointerMove);renderer.domElement.addEventListener('pointerup',pointerUp);renderer.domElement.addEventListener('pointerleave',()=>{tip.hidden=true});
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('label-leaders');el.appendChild(svg);const leader=document.createElementNS(svg.namespaceURI,'line');svg.appendChild(leader);const clock=new T.Clock(),projected=new T.Vector3();
 function animate(){if(dead)return;frame=requestAnimationFrame(animate);const s=latest.current,dt=Math.min(clock.getDelta(),.05);if(loaded){if(s.hideNames)tip.hidden=true;updateSections(s);leader.setAttribute('visibility','hidden');const nextKey=s.preset+s.plane+s.region+s.visible.join('|')+s.brainOnly+s.isolate+s.selected+camera.aspect.toFixed(3);if(nextKey!==key){layout();key=nextKey}const targetExplode=s.plane==='none'?s.explode:0;const moving=Math.abs(amount-targetExplode)>.0001;amount=window.matchMedia('(prefers-reduced-motion: reduce)').matches?targetExplode:moving?T.MathUtils.damp(amount,targetExplode,7,dt):targetExplode;atlas.parts.forEach((p,i)=>{const mesh=meshes[i],selected=p.id===s.selected,highlighted=selected||s.highlight.includes(p.id);mesh.visible=shown(p,s);mesh.position.copy(targets[i]).sub(centers[i]).multiplyScalar(amount);materials[i].color.set(highlighted?'#24d8e5':s.highContrast?studyCategory(p).color:s.natural&&s.plane==='none'?(p.group==='Blood supply'?'#b8555f':p.group==='Ventricles'?'#8cbacf':p.group==='White matter'?'#ded5bd':p.group==='Meninges'?'#d6cbb9':p.group==='Cortex'?'#b99791':p.group==='Spinal cord'?'#d7c5a7':'#c6ada3'):p.color);materials[i].emissive.set(highlighted?'#087d99':'#000000');materials[i].emissiveIntensity=highlighted?.45:0;const label=labels[i];label.textContent=s.hideNames?'Selected structure':p.name;label.hidden=!(mesh.visible&&mesh.geometry.getAttribute('position').count>0&&((!s.hideNames&&s.labels&&amount>.8)||selected));if(!label.hidden){projected.copy(s.plane!=='none'&&mesh.geometry.boundingSphere?mesh.geometry.boundingSphere.center:centers[i]).add(mesh.position).project(camera);const px=(projected.x+1)*el.clientWidth/2,py=(1-projected.y)*el.clientHeight/2;label.style.left=(selected?12:px)+'px';label.style.top=(selected?el.clientHeight-58:py+17)+'px';if(selected){leader.setAttribute('x1','100');leader.setAttribute('y1',String(el.clientHeight-46));leader.setAttribute('x2',String(px));leader.setAttribute('y2',String(py));leader.setAttribute('visibility','visible')}label.hidden=projected.z>1||projected.z< -1;label.classList.toggle('selected',selected)}});const focus=s.preset+s.plane+s.region+s.reset+s.view+s.isolate+(s.isolate?s.selected:'')+s.brainOnly+s.visible.join('|');if(focus!==lastFocus||moving){fit();lastFocus=focus}pedestal.visible=s.plane==='none'&&s.preset==='full'&&amount<.25&&!s.brainOnly&&!s.isolate;pedestal.scale.setScalar(1-amount);controls.autoRotate=s.rotate&&s.plane==='none';controls.enableRotate=s.plane==='none';}controls.update();renderer.render(scene,camera)}animate();
 return()=>{dead=true;abort.abort();cancelAnimationFrame(frame);observer.disconnect();controls.dispose();cuts.forEach(g=>g.dispose());geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());disc.geometry.dispose();(disc.material as T.Material).dispose();ring.geometry.dispose();(ring.material as T.Material).dispose();renderer.dispose();renderer.domElement.remove();labelRoot.remove();tip.remove();svg.remove()};
 },[atlas]);return <div className="canvas-host" ref={host}/>;
}
